! FVPRECISION - FVWBM PRECISION DEFINITION MODULE
!
! Copyright WBM 2007
! Authors: Ian Teakle

MODULE PRECISION
!!DEC$ STRICT

INCLUDE 'COMPILER_DIRECTIVES.FI'

IMPLICIT NONE

! SET DEFINED KIND SIZES
!DEC$ IF (_PRECISION==1)
INTEGER,PARAMETER :: ISGL = 4
INTEGER,PARAMETER :: SGL = 4
INTEGER,PARAMETER :: DBL = 8
!DEC$ ELSE IF (_PRECISION==2)
INTEGER,PARAMETER :: ISGL = 4
INTEGER,PARAMETER :: SGL = 8
INTEGER,PARAMETER :: DBL = 8
!DEC$ END IF

! SET NAN PARAMETER
REAL(KIND=SGL),PARAMETER :: NAN_SGL = 0._SGL/0._SGL
REAL(KIND=DBL),PARAMETER :: NAN_DBL = 0._DBL/0._DBL

! SET DEFINED CHARACTER LENGTH PARAMETERS
INTEGER,PARAMETER :: SSTR = 30                              ! SHORT STRING LENGTH
INTEGER,PARAMETER :: MSTR = 80                              ! MEDIUM STRING LENGTH
INTEGER,PARAMETER :: LSTR = 200                             ! LONG STRING LENGTH

END MODULE PRECISION
